apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: go-hello
  template:
    metadata:
      labels:
        app: go-hello
    spec:
      containers:
        - name: go-hello
          image: go-hello
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: go-hello-svc
spec:
  ports:
    - port: 8080
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: go-hello
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-hello-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: go-hello-svc
    servicePort: 8080
