resources:
  - name: ee-kube-git
    type: git
    source:
      uri: http://github.com/jmylchreest/ee-kube.git
      branch: master
  - name: ee-kube-dockerhub-image
    type: docker-image
    source:
      repository: jmylchreest/ee-kube
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
  - name: job-build-test
    plan:
      - get: ee-kube-git
        trigger: true
      - task: task-build-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golang
          inputs:
            - name: ee-kube-git
          run:
            dir: ee-kube-git
            path: ci/scripts/build.sh
          outputs:
            - name: ee-kube-git-tested      
  - name: job-build-push-image
    plan:
      - get: ee-kube-git
        passed: [job-build-test]
      - put: ee-kube-dockerhub-image
        params:
          build: ee-kube-git-tested